apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-fe
  template:
    metadata:
      labels:
        app: devops-fe
    spec:
      containers:
        - name: devops-fe
          image: aaditya4959/devops-fe:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-fe-service
spec:
  selector:
    app: devops-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer